modrinth/knossos

.gitattributes

By default git checks lines out with dos line endings on Windows.
*prettier* doesn't like these and will complain about these in the `.vue` files.
The `.gitattributes` file will check out all vue files with unix line endings.
Love to write one line prs ^^

Add line ending configuration

---

nuxt.config.js
pages/mod/_id/index.vue
pages/mod/_id/version/_version.vue
pages/mod/_id/versions.vue

This switches around the meta tags to make embeds work.
There are still two issues:
1. It would be nice to be able to set the `author` meta tag properly; This requires processing the members list to find if it has a single author, or taking a team name instead.  I don't have the knowledge of this setup to make that change.
2. Currently the normal `description` tag has the mod's description with an appended statement about modrinth.  You should make that string constant somehow so that you can change it without modifying every page.

Fix meta tags for embeds

---

pages/mods.vue

This makes the frontend respect the `latest_version` returned in search results.  This does not change the latest-version displayed on a user's profile though, since that is already incorrect and doesn't retrieve to the versions listing.

Fix latest version listing

---

components/Pagination.vue

This has the effect of the cursor being shown when hovering over
the previous button.

Apply 'active-paginate' to Previous button

---

.vscode/settings.json
pages/mod/_id/index.vue
pages/mod/_id/settings.vue
pages/mod/_id/version/_version.vue
pages/mod/_id/versions.vue

Before:
- If a version was in processing, it would cause axios to throw a 404 error. 
After:
- When a 404 error is thrown, it is ignored.
You could maybe document which versions were processing and add them to the versions list as "processing"

Avoid 404 page while version is processed 

---

layouts/default.vue

Really makes a big difference than before.

Add small ease-in-out transition between pages.

---

plugins/compiled-markdown-directive.js

This PR adds `summary` tags to XSS's whitelist. Previously, they were escaped, meaning that dropdowns could only have "Details" as the title. Here's an example of it working:

Fix summary tags being always escaped by XSS

---

components/ModPage.vue

This PR fix the fact that Discord and Wiki external links do not open a new tab

Fix Discord and Wiki external link does not open new tab

---

plugins/compiled-markdown-directive.js

This pr allows the `id` through the xss filter but prefixes them with `user-generated-`. A script has been added to convert the location hash in the url to the correct id in the page. It also handles repeatedly pressing a link to an anchor.
fixes #112

Implement header ids

---

layouts/default.vue

Fixes issue #85.
Since I couldn't really try this out in dev (I don't know how to login without GitHub lol) this should be tested before merging.
**How:** Mostly set the `min-width` of `.user-controls` and made the child elements use the full space.
**Addtional Notes:** It might make sense to center the user name on the button but I don't really know ¯\\\_(ツ)\_/¯
**Before:**
**After:**

Fix #85 (Notification icon sized incorrectly for short user names)

---

pages/user/_id.vue

Reverts modrinth/knossos#220
This check on the buttons DIV:
```js
v-if="this.$auth.user.id != user.id"
```
Occurs before this check on the button:
```js
v-if="this.$auth.user"
```
This causes an error because `this.$auth.user.id` is undefined when the user is not logged in. Both checks should be moved to either the button or DIV where:
```js
v-if="this.$auth.user && this.$auth.user.id != user.id"
```

Revert "Fix report button on own uer page"

---

middleware/auth.js
pages/dashboard/misc/revoke-token.vue

Fixes a 404 error when trying to visit a page that requires you to be logged in.
Fixes the logout button on the revoke token page.

Remove all uses of `process.env.domain`

---

pages/dashboard/notifications.vue

```js
if (index) {
const config = {
method: notification.actions[index].action_route[0].toLowerCase(),
url: `${notification.actions[index].action_route[1]}`,
headers: {
Authorization: this.$auth.token,
},
}
await this.$axios(config)
}
```
Due to the IF statement in the code above, (in the part that performs a notification action), if the notification is the first in the array (the most recent notification) the IF statement will fail, preventing the request from happening, while still deleting the notification. This is the source of many team member invite issues.
The PR changes the line to:
```js
if (typeof index !== 'undefined') {
```

Fix first notification not performing action

---

pages/mod/_id/edit.vue
pages/mod/create.vue

This is not a nice fix though because it leads to code duplication.

Fix #237 by alphabetically sorting the licenses

---

assets/styles/components.scss
assets/styles/global.scss

-----
----
----
Code blocks with long lines still cause styling problems. I did make them scrollable though.

Markdown styling fixes

---

pages/dashboard/moderation.vue
pages/mod/_id/edit.vue
pages/mod/create.vue

This PR fixes reports on the moderation dashboard going to `/dashboard/mod/_id` instead of to `/mod/_id`.
It also allows the ability for moderators to unlist mods in the queue from the frontend instead of having to do it via the backend.
Unlisted mods should have the ability to resubmit for approval, so I've also changed "Submit for Review" to "Submit for approval", allowing unlisted mods to do that as well.

Fix a bug & add improvements to a couple moderation aspects

---

pages/legal/rules.vue
pages/legal/terms.vue

This adds the project guidelines as outlined [here](https://discord.com/channels/734077874708938864/734077874708938867/806556531491471368) to the Terms page.
NOTE: I've made a few tweaks in wording to accommodate this format, so this is not an exact copy.
Among changes that I've made to Pros's original document (not fully comprehensive):
- "mod" reworded to "Project" if applicable
- Clarified that projects are content
- Some wording has been clarified (e.g. "auto pvp" to "automatic PvP" or "item duping" to "item duplication"
- Oxford comma added in at least one place
---
A deploy can be found at https://knossos-git-project-guidelines-emmaffle.vercel.app/legal/terms.

Add project guidelines to Terms page

---

layouts/default.vue

Removes the query, `?q=` from the login URL.
Closes #256

Allow users to login from search page when it is rendered serverside

---

pages/mod/_id/newversion.vue
pages/mod/_id/version/_version/index.vue

This allows the file selector to be correct across operating systems, and also brings parity between the file selector on newversion and version index.
Supersedes #280

Improve MIME type detection (fixes #279)

---

pages/mod/_id/edit.vue

This fixes a bug where the "Submit for approval" button was always present no matter the project status.
These things are finnicky.

Fix a bug introduced in #278 ("submit for approval" always being present)

---

plugins/compiled-markdown-directive.js

Currently the XSS filter doesn't allow iframes. This PR allows iframes that come from specific sources, YouTube embeds. The `allowedSources` array contains all allowed sources. Source's are matched by checking a regex expression against the iframe's `src` url.
Youtube autoplay is disabled.
In addition, this PR extends the default markdown image syntax. Images with youtube links are autodetected and transformed into youtube embeds. The following is acceptable markdown syntax:
```
```

Allow Youtube through iframes + using image syntax in markdown

---

pages/index.vue

This PR is small (yes my all PR are smalls ^^) but he change the link of doc on main page for v2 (github wiki to https://docs.modrinth.com/docs/intro/).
Done this for v1 is maybe useless...

Change doc url on main page

---

assets/styles/components.scss
assets/styles/global.scss
libs/getDifferences.js
package-lock.json
pages/mod/_id/edit.vue
pages/mod/_id/settings.vue

Instead of sending everything to the backend when editing a mod, this keeps track of the old mod data and before uploading checks the differences between them. Then it only uploads the changes.
Importantly, this fixes an issue where team members with the permission to change the mod body are denied when using knossos. (I would assume the issue also exists the other way around.)
Everything relating to donation links is commented out.
The preview mod icon is smaller.

Makes mod editing only send changed data

---

nuxt.config.js
static/opensearch.xml

For more about OpenSearch, see [the official spec](https://github.com/dewitt/opensearch/blob/master/opensearch-1-1-draft-6.md) or the [Mozilla dev wiki page](https://developer.mozilla.org/en-US/docs/Web/OpenSearch).
Video demonstration: https://streamable.com/r7ct7c

Add OpenSearch for searching mods in browser bar

---

pages/_type/_id/version.vue

It's now larger by default and is resizable:

Fix changelog textarea being unusably small

---

layouts/default.vue

Closes #368 
Desktop implementation:
Mobile implementation:
Since the Mobile menu is getting crowded, I implemented scrolling on it if the device screen is not tall enough. We need to come up with a better layout for this most likely at some point.

Add easier access to the Following page and add scroll support to mobile overflow menu

---

layouts/default.vue
pages/search.vue

This PR adds skip links to all pages which act as the first tab stop on the page to improve accessibility (https://a11y-101.com/development/skip-link)
On the search page it also adds another skip link to directly jump to the search results.
The skip links are currently styled the same way as the GitHub login button however they currently aren't horizontally aligned. The method used to add the second skip link for the search page is also a bit ugly as it uses global event listeners.

Add skip links

---

components/ui/Checkbox.vue
components/ui/search/Categories.vue
pages/search.vue

As a temporary workaround until we get the ability to "feature" loaders and give them display names, these changes add the following things:
A "More" button to show more loaders that are hidden by default
ModLoader is now capitalized properly

Loader workarounds due to missing backend changes

---

components/ui/ProjectCard.vue

Fixes some overlap on cards
Before:
After:

Mobile category overlap fix

---

pages/index.vue

On iOS when navigating to the homepage from a different page, the search videos immediately go full screen (even if they're hidden) which is annoying.

iOS video fix

---

components/ui/ProjectCard.vue
pages/_type/_id.vue

This adds a tooltip that appears whenever you hover over the Created/Updated text in search results and mod pages. Example:

Add date tooltips

---

components/ui/StatelessFileInput.vue
pages/_type/_id/version.vue

Resolves #536 
In short, state was being duplicated (in the form and in the component). This component has no internal state. Instead, it lets the caller handle state management (communicating additions via the `change` event).

Create `StatelessFileInput`, use in version.vue

---

components/ui/SmartFileInput.vue
components/ui/StatelessFileInput.vue
plugins/fileUtils.js
plugins/shorthands.js

This should give `StatelessFileInput` feature parity with `SmartFileInput`.
- created `fileUtils.js` for shared logic between the two components. (not sure this belongs in `plugins` dir, but I wasn't confident in anything existing being more suitable. lmk if you think there is a better place.)
- exported static utils from `plugins/shorthands.js` so that they can be used w/o vue context
- `formatNumber`
- `formatBytes`

StatelessFIleInput: add `maxSize` and `showIcon`

---

components/ui/VersionFilterControl.vue
pages/search.vue

Also adds `scoped` to `VersionFilterControl`'s `<style>` tag, it was causing differences between dev and prod.

Broken mobile search fix

---

.github/ISSUE_TEMPLATE/config.yml

Adds a config.yml to `.github/ISSUE_TEMPLATE/` which allows to show links to useful pages.
I decided to include the GitHub Invite and Modrinth documentation page. If any other pages should be added, let me know.
I also left `blank_issues_enabled` on true. If that should be changed, let me know too.

Create config.yml for issue selection

---

components/ui/ProjectCard.vue
pages/_type/_id.vue
pages/user/_id.vue

Implemented #540 and now the cursor does not change to "text" on hoverable "date" fields. Instead, it remains the "default" cursor.
I think it looks cleaner, but I can remove it if the Modrinth Team doesn't like it.

Hoverable "joined" fields on user pages

---

plugins/xss.js

Allows to apply `style` attribute to `<img>` tags with value `image-rendering` set to `pixelated`, which can be useful for people who use pixel art in their READMEs (to demonstrate items, for example).
As asked on Discord:
<picture>
<source media="(prefers-color-scheme: dark)" srcset="https://user-images.githubusercontent.com/10401817/183349652-f9fa9f5e-9230-43f7-8254-40659e034bf4.png">
I would like to have a thing that scrolls through all the possible fish without requiring users to download a colossal gif. [Example code snippet]’." src="https://user-images.githubusercontent.com/10401817/183349685-251d20cd-66db-428b-90d6-7de76cd6601f.png">
</picture>
Example code:
```md
```
---
Not sure if any pull requests are accepted to this branch or should go to other branch like `master`, but tell …

Allow setting pixelated image-rendering

---

pages/create/project.vue

Asterisk next to description label for the section in project creation page was wrapping at resolutions lower than 1024 pixels, fixed by setting flex-direction: row
before: 
after:

Fixed description * wrap in project create page

---

pages/_type/_id.vue

A couple of friends and I who started using Modrinth recently didn't realize the "versions" tab existed right away. This PR aims to provide a way for users to easily find and access the "versions" tab from the "featured versions" section.

Add "See all" link next to featured versions

---

assets/styles/components.scss

This PR adds support for image URLs suffixed with `#gh-dark-mode-only` and `#gh-light-mode-only`, enhancing compatibility with GitHub README Markdown descriptions.

Add support for GitHub-styled color scheme dependent images

---

assets/images/utils/chevron-right.svg
assets/styles/global.scss
pages/_type/_id.vue

This pull request improves the design of the "See all" link in the featured versions section. Previously it used to be a link in parentheses next to the heading, which did not look great and didn't semantically make sense. Now the link is separated, aligned to the right and has chevron to make it look like a clickable object. The clickable area has been increased too, and is displayed on hover.
<table>
<tr>
<th>Light mode</th>
<th>Dark mode</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/10401817/186482894-a40c4937-bbbc-49a3-9f2e-c0d8a2cc5bb0.jpg" alt="Preview of the link in light mode." align="center"></td>
<td><img src="https://user-images.githubusercontent.com/10401817/186482901-90981e10-483b-4745-882f-fa7c584ed844.jpg" alt="Preview of the link in dark mode." …

Improve design of "See all" link in feat. section

---

pages/_type/_id/version.vue
pages/create/project.vue

It is somewhat annoying when the dropdown closes after selecting a loader for a (new) version, as you have to constantly click it again to select additional loaders (i.e. Waterfall if you selected BungeeCord before).
This PR changes this. I hope I changed all the right places...

Don't close dropdown when selecting loaders

---

components/ads/Advertisement.vue

Ever since changes for Carbon ads were introduced, the label did not match the appearance of the card, leaving the bottom right corner of the card not round. With more recent changes, where border was added, that became even more apparent - now the border covers the label, which does not look good; this effect only becomes worse when zooming.
This commit attempts to mitigate these issues with the following:
- To fix the border issues, label's absolute position is now calculated from the card wrapper, where the border is applied. This allows label to cover the border for seamless look. That is done by changing position of the card wrapper to relative instead of doing so for the ad contents container.
- The label now tries to take over the border, to do so the bottom and right relative …

Fix advertisement label look

---

pages/_type/_id.vue

- Now styled as a proper link.
- Change :focus to :focus-visible to avoid link getting stuck in that 'hovered' state because focus does not actually change (it deffo should though, something to fix in the future - should be one fragment change).
- Removed all padding and transition.
<table>
<tr>
<th>State</th>
<th>Light mode</th>
<th>Dark mode</th>
</tr>
<tr>
<td align="center">Normal</td>
<td align="center"><img src="https://user-images.githubusercontent.com/10401817/186906103-cbeac783-3df3-4bba-8c2c-2be4ff9582e2.png" alt="Preview of normal link state in light theme." align="center"></td>
<td align="center"><img src="https://user-images.githubusercontent.com/10401817/186906421-9f57c204-cfca-431c-9a75-3e72e52323d7.png" alt="Preview of normal link state in dark theme." align="center"></td> …

Minor fixes for "See all" link design

---

components/ads/Advertisement.vue

Detecting that ad has failed to load with timeout is not accurate and won't work on slow connections. This commit fixes that by changing detection to use 'onerror' event on <script> tag instead, which will be triggered if ad script fails to load due to blocking.

More reliably detect ad load faults

---

package-lock.json
package.json

This does not affect the site in any way except that the color preference is no longer stored using the cookies, it's only localStorage now.

Bump @nuxtjs/color-mode to v2.1.1

---

components/ui/CopyCode.vue
pages/_type/_id.vue

makes the font slightly smaller and removes the base button margin in order to fit in with the overall layout :D
before:
after:

Improve project ID display

---

components/ui/NavRow.vue

For example, when clicking on e.g. "Mods" the navigation line will appear instantly. Then when clicking on the Modrinth logo, the navigation line will disappear. However, when then clicking on e.g. "Plugins", the line will first appear underneath "Mods" and then move to "Plugins", even though "Mods" was not previously selected. 
This fixes that behavior and causes the line to instantly appear under "Plugins".

Properly reset NavRow animation

---

pages/search.vue

Moves the filters button to be to the left of the search bar on mobile screens. 
When the filters menu is opened, it appears below the search card.

Move filters menu on mobile

---

assets/styles/global.scss
layouts/default.vue
pages/search.vue

Fixes search input on non-mobile screens to be full width, also fixes a few other tiny things: fixes round inputs on iOS, changes filters button to use box-shadow instead of outline so it is round on iOS, and fixes the hamburger menu not covering the entire screen.

Fix search input, other things

---

assets/styles/components.scss

This removes the empty space that are inside `<details>`'s end:
The below has been addressed on the refined version of the fix
<details>
<summary>Outdated note</summary>
Do note that if the `<details>` is improperly formatted, then this fix will slightly break it even further, although considered that it's already broken, I don't believe that this outweighs the benefits of the fix;
</details>
(dev note: why is node.js v16 required when v18 is already LTS ;-;)

Remove bottom padding on <details>' last element

---

layouts/default.vue

Should fix the overlay of the iPhone navigation gestures. I cannot test it though as I do not own such a device.

Use safe insets on bottom of screen

---

layouts/default.vue
pages/settings/account.vue

We're like half asleep and totally open to actual design people picking different wording for these strings, but I'm not super familiar with who's on the designs team and how to get in contact with them so this seemed like a good direct way.
Anyway this pr does [drumroll]
becomes 
becomes
not super fussed on the second string seeing as we'll never see it but we included it for comprehensiveness
that's it,

Re-word "my profile" to "your profile"/"this profile"

---

store/user.js

In actions of user Vuex store, calling an action to fetch notifications would fetch them correctly, but store them in place of user follows, which resulted in funkiness when switching from notifications to follows page (because Vue would render project cards for notifications data before the actual follows were fetched correctly).

Fix notifications fetching

---

pages/search.vue

Now you may officially no longer install modpack support.

Fix a small wording mistake

---

pages/index.vue

Currently, the space to the right of the `open-source` link on the homepage is underlined as part of the link.  This simply corrects that by matching the `fully documented` link.

fix "open-source" link on homepage's whitespace

---

components/ui/VersionFilterControl.vue

This PR adds two query parameters to the *Versions* and *Changelog* sections.
Selecting and unselecting loader and Minecraft versions dynamically updates the query parameters.
Refreshing the page or sharing the link with filters active will automatically apply the filters.
Nonexistent loaders or Minecraft versions will automatically be removed on page load.
https://user-images.githubusercontent.com/13237524/197406455-91a404d9-5bc0-4774-8d25-f2da74c7432e.mp4
This closes #603

Persistent version filters

---

pages/_type/_id/changelog.vue

Change display to block from flex to fix content overflow on the changelog page.

Change 'changelog-item' display to block from flex.

---

pages/_type/_id.vue
pages/user/_id.vue

Related to #771 this makes project and profile descriptions wrap very long words or long links.
Unlikely to be seen but for example descriptions that refer to minecraft bugs (https://modrinth.com/mod/entity-collision-fps-fix) are close to overflowing on 1080p screens and do on small screens.
with fix applied:

Make summaries and bios wrap

---

pages/index.vue

Fixes #857
Also gives them the scale animation all the other clickable elements on the site have.

Make landing page project cards use actual links instead of JS

---

components/ui/ProjectCard.vue

The reason for this is that it ruins the aesthetic of and misrepresents many shader packs. The dimming is kept for project colors.

Remove dimming of featured gallery images in project cards

---

assets/styles/components.scss

The new ones use consistent colors and styling with the page. They weren't being shown properly in production due to some weirdness with the library. Adding !important fixes that.

Overwrite default notification colors with !important

---

plugins/fileUtils.js

Removes any leading numbers from the mod ID that is generated from the project's slug for data pack -> mod conversion
Fixes #845

Remove numbers at the start of slugs when converting to mod ID

---

pages/search.vue

On grid mode, it will have these options which are even multiples of 3:
While gallery mode has all even options:
Also fixes #829

Balance search pages to have view mode-aware max search results

---

pages/_type/_id/settings/license.vue

Pretty sure this was the intended functionality of this, it'll replace spaces in custom license names with `-` for the ID

Fix custom license erroring with spaces

---

.github/workflows/nuxt.yml

This is the last version Nuxt 2 supports.

GitHub Actions: Use Node 16 to build Knossos

---

pages/_type/_id/changelog.vue
plugins/shorthands.js

Previously, if let's say you have a fabric and forge version and the forge version was the duplicate, if you changed it to filter by forge, the changelogs would not show because fabric was the non-duplicate, which is no longer shown.

Recalculate changelog deduplication when the filters change

---

components/ui/Modal.vue

Fixes #962
This bug was caused by issues with using transform on text elements. I opted to use a flexbox container to
position the modal in the center without using transforms, which eliminates this issue. From the testing I've done
so far, this produces an identical effect, just without the blurring.
Old version:
Fixed version:

Fix modal text getting blurred from transforms in chromium on some devices (fix #962)

---

components/ui/Pagination.vue

Fixes #968 
Sets `tabindex="-1"` on disabled pagination buttons to prevent users from tabbing to them.

Disable tabbing to pagination arrows when they are disabled (fixes #968)

---

pages/search/[type].vue

Fixes #963 
This PR move the "No results for your query" text outside of the grid so that it is consistently centered.
List view:
Current grid view: 
New grid view: 
(The same applies for the gallery view as well)

Make position of the "no results" text on grid/gallery views consistent (fixes #963)

---

assets/styles/components.scss

Fixes #969
The dropdown component uses a span to display placeholder text until it is focused, then it uses a normal input placeholder.
The margin on the span element was 10px, and the input had 8px, causing a layout shift whenever the multiselect was focused. The placeholder also had a line-height of 20px which made the text appear off-center, so I adjusted it to 16px.

Adjust dropdown layout shift and placeholder line height (Fixes #969)

---

pages/index.vue

Fixes #893 
With height being changed to min-height, the container can resize as necessary.

Changes demo-search height to be min-height.

---

pages/user/[id].vue

Resolves #914 
Media query will push username down once Report button is somewhat close to it. I chose 400px because the Report button was already overlapping Geometrically's username by 400.

Adds media query style to prevent Report button from overlapping username.

---

pages/[type]/[id].vue
pages/[type]/[id]/versions.vue

Closes #949.
Since the button does a router push, the page just instantly loads at all-versions. A more clever solution can be concocted later, but this should at least make using the button less egregious when on the versions page.

See all versions will navigate to versions#all-versions.

---

pages/[type]/[id]/versions.vue

Closes #682 
Brings in the code we had in [id].vue to the versions page.

Formats version text based on count.

---

pages/[type]/[id].vue

In the "Project members" section of a project page, each team member is a `div` with a click handler to change the URL, rather than a `nuxt-link` element, which would be a better option to use here.
* This allows right-click and middle-click actions to work, such as opening in a new tab or copying the link.
* Makes more sense semantically.
* Doesn't require JS.
Hope I did this right, this is my first time contributing to a Vue project.

Use nuxt-link for team member element

---

composables/user.js
pages/[type]/[id].vue

**Description:**
Ensures the project followers on the client side is in-sync with the actions taken.
**Media:**
https://user-images.githubusercontent.com/32039051/224480515-ef39e6ba-55ac-455f-885e-56efd42607cd.mov
Closes: #437

fix(project): update follower count client side

---

assets/styles/components.scss
assets/styles/global.scss
components/ui/FileInput.vue

This seems to fix #1042. I did notice an additional bug, which is that the cursor does not change to `not-allowed` when disabled. This seems to be a browser bug that I guess was just never fixed? https://stackoverflow.com/questions/1537223/change-cursor-type-on-input-type-file

Fix disabled css selector Closes #1042

---

components/ui/Avatar.vue

Technically this was already implemented, but it was really janky and didn't always work if the images were cached iirc. This fix seems to work all the time. Closes #289

Make pixel art more reliably get pixelated rendering

---

pages/[type]/[id]/settings/index.vue
pages/dashboard/projects.vue

Fixes the projects page in dashboard linking to the actual project type instead of the inferred one, fix display of project type in slug field Closes #1066

Fix project type in Dashboard & settings URLs Closes #1066

---

pages/[type]/[id]/changelog.vue

Fix changelog-bar overflowing

---

helpers/parse.js

I propose that project descriptions should be able to utilize HTML image maps. Because projects are already required to have adequate accessibility for screen readers, projects with images that currently have multiple images with multiple links can now streamline that process by having one image with an image map.
Pros
* Does not harm accessibility
* More flexible and engaging descriptions that utilize images
* Unique feature not supported by many other platforms
Cons
* Whitelisting new tags always increases the theoretical chance of XSS
* I believe this to be minimal because this proposal extends the already-accepted `a` tags for `areas` and only adds additional declarative attributes with no new interpretable ones.

Support HTML image maps

---

assets/styles/components.scss

Currently, images are treated as text in markdown, and text-related attributes are affecting layout (line height, etc.). This proposal fixes that issue by enforcing native image layout. This also prevents inline images without text between them from generating extra whitespace between them, allowing seamless images.
Before:
After:

Prevent images from being treated as text in markdown

---

helpers/parse.js

As per request from discord https://discord.com/channels/734077874708938864/783153806531100673/1100549312737452102
I've added the `bstats.org` as a trusted source, to not cache graphs from there.
Before:
After:

add bstats.org as allowed domain name for markdown

---

helpers/parse.js

[cf.way2muchnoise.eu](https://cf.way2muchnoise.eu/) provides badges for stats on curseforge. They are somewhat commonly used in modrinth project descriptions. Due to the current caching they easily become very outdated. In one case the badge in [extended drawers](https://modrinth.com/mod/extended-drawers) description shows about 100K less downloads when viewed on modrinth compared to other platforms ([github](https://github.com/MattiDragon/ExtendedDrawers) and [curseforge](https://www.curseforge.com/minecraft/mc-mods/extended-drawers)). 
This change disables caching for these badges to ensure they stay up to date.

Add cf.way2muchnoise.eu as allowed image domain

---

helpers/parse.js

**Description:**
(This has been copied from #1001 verbatim)
The previous regex ONLY allowed for youtube embeds to have the query param autoplay, meaning when embedding youtube videos, people would have to manually sort through their src url to remove unwanted properties. (This is also not wanted, since the start is a very useful prop for these types of videos, if the real tutorial/showcase begins 2 minutes in.
The following regex works for any query parameters.
^https?:\/\/(www\.)?youtube(-nocookie)?\.com\/embed\/[a-zA-Z0-9_-]{11}(\?(&?\w+=(\w|\d)+)+)?$
(This setup then works as a default blacklist approach, where any non-wanted query parameters should be added to the remove section).
Simply due to the nature of regex, that requires the position of strings to match, or just matching 3 …

 fix(xss): allow any query parameters in youtube embed, ported from #1001

---

pages/[type]/[id]/settings/index.vue

Replaces the following text:
> Set the visibility of your project. Listed and archived projects are visible in search. 
Unlisted projects are published, but not visible in search or on user profiles. 
Private projects are only accessible by members of the project.
With some indicators that are much easier to understand.
Potentially could word differently? Not sure if the following should be used instead for the search and member profile bulletpoint
- Visible in search results
- Visible on member profiles

Add indicators for visibility on project settings page

---

helpers/parse.js

This changes the XSS parser to allow `td` and `th` to have the `style` attribute, and also readds support for `img` to have the `style` attribute too with the proper whitelist.
This also makes it so that `text-align` style is whitelisted for use which fixes #1175

Fix table styling

---

nuxt.config.ts
package.json
pnpm-lock.yaml

This is a new resolution algorithm in TypeScript that closely matches the one found in popular bundlers like Vite and Webpack.
Switching to it is recommended since more and more packages are using `exports` maps, which outdated `node` resolution does not support.
Nuxt added support for this resolution in [3.5.0](https://github.com/nuxt/nuxt/releases/tag/v3.5.0), so it was explicitly updated. Along it were updated the TypeScript-related dependencies, since `bundler` resolution was only added in TypeScript 5.
More details:
https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#moduleresolution-bundler
https://github.com/microsoft/TypeScript/pull/51669

Switch to bundler TypeScript moduleResolution

---

pages/[type]/[id].vue

after the change i did in #1189 it broke the layout of the featured version.
the final DOM made no sense, as the content inside of the main `NuxtLink` was being generated outside of it, the fix was to only render it on the client side, as i believe it was a server render mismatch issue.
Fixed version:

fix: featured version ui shifts

---

layouts/default.vue

fix: #1164 
Issue:
- when u have the toolbar url set to the top and u scroll inside the page, the bottom mobile navigation seems to change height, due to the padding thats set.
fixed version:

fixed mobile navigation on iphones safari

---

plugins/shorthands.js

An en dash is the appropriate punctuation for ranges (numbers, dates, versions).
Closes #1245

Use en dash for versions range instead of em dash

---

.github/workflows/deploy.yml

GitHub disables workflows on forks by default, but for those folks like me who need actions to be enabled for test deploys, having Modrinth's own workflows failing is annoying. This should change it so that Deploy workflow only runs for repositories owned by Modrinth (thus this repository).

Don't run Deploy workflow on forks

---

helpers/infer.js
package.json
pnpm-lock.yaml

This changes the infer to support all of semver by instead of handling semver ranges manually it uses the npm `node-semver` package.
This also adds support for forges maven ranges by converting maven ranges to semver ranges and passing them to the semver version range handling to get the game versions.
Supersedes #1161

Change version infering to use full semver range spec

---

pages/app.vue

I found a little spelling mistake in /app, here's a fix lmao

Fix spelling mistake (accross -> across)

---

helpers/infer.js

Added metadata inference support for Paper Plugins ([`paper-plugin.yml`](https://docs.papermc.io/paper/dev/getting-started/paper-plugins))

Added metadata inference support for Paper Plugins

---

components/ui/report/ReportsList.vue
pages/dashboard/reports.vue

Add some text for when you haven't filed any reports, helps the reports page fit in with the other dashboard pages.
Closes https://github.com/modrinth/knossos/issues/1270

Add some text for when you haven't filed any reports

---

components/ui/ProjectCard.vue
pages/[type]/[id].vue

#1280
Icons in project pages with featured images and in search results with gallery view have borders that resize them from 96x96 to 88x92.
These box-shadow replacements preserve icon size while retaining visual equivalency (rounded 4px border around left, top, and right).

Replace project icon borders

---

pages/settings.vue

Moves "Languages" menu to be under "Appearance" section (where it supposed to be but landed itself in "User settings" due to poor rebase). Also hides it from production for now, as no languages are currently enabled.

Move language navigation menu item and hide it in production

---

pages/[type]/[id]/changelog.vue

I also fixed that `.markdown-body` style not applying normally

Improve download button in changelog

---

pages/auth/sign-in.vue

This PR add support to detecting enter key for 2FA input field (this improve the user experience).
I use keyup event because keypress is deprecated (https://developer.mozilla.org/en-US/docs/Web/API/Element/keypress_event).

Support enter key for 2FA input field

---

locales/en-US/index.json
pages/settings/language.vue

This caused confusion to translators, and it doesn't seem like it would change in most of the languages. If there's going to be a need to make it use different formatting in some language, this can be easily reverted.

Make language label not translatable

---

pages/auth/reset-password.vue
pages/auth/sign-in.vue
pages/auth/sign-up.vue
pages/settings/account.vue

Currently, none of the email, username or password inputs on authentication-related pages include [`autocomplete` attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete). This means that autocompletion and password management tools provided by the browser or browser extensions have to guess the meaning of each form field.
This PR adds the appropriate attributes to the aforementioned input elements on the sign-up, sign-in, reset password, and user settings (for changing your password) pages. This lets browsers reliably provide autofill suggestions, making it easier and quicker to use those forms. It should also let some browsers suggest a randomly-generated password when a user creates a Modrinth account.
I've also changed the `type` attribute of the email …

Add `autocomplete` attributes to auth-related inputs 

---

pages/user/[id].vue

Fix: Mistake for profile translations

---

nuxt.config.ts
package.json
pnpm-lock.yaml

- Update @vintl/nuxt to v1.5.0 (compare: [source](https://github.com/vintl-dev/nuxt/compare/%40vintl/nuxt%401.3.0...%40vintl/nuxt%401.5.0) · [package](https://renovatebot.com/diffs/npm/@vintl%2fnuxt/1.3.0/1.5.0))
- Try improving i18n-related SEO
- Change the hreflang tag for `en-US` locale to a more generic `en` (English) from the `en-US` (English as spoken in USA).
- Disable the host language parameter for the default locale

Try improving i18n-related SEO

---

pages/[type]/[id]/settings/license.vue

Closes #1324
When using backspace on the license multiselect element, it will set license to null and break, fixed this using optional chaining and some other checks.

Fix license element deleting itself when pressing backspace.

---

pages/[type]/[id]/version/[version].vue

Closes #1307
Move `deps()` from setup to computed so that the dependencies list actually updates visually when removing a dependency.
[From Vue 3 docs.](https://vuejs.org/guide/essentials/list.html#displaying-filtered-sorted-results)

Fix dependencies list not updating on dependency remove.

---

pages/settings/account.vue

Closes #1268
Disables the save/remove button in the change/add/remove password modal for better UX.

Disable save & remove password button when no input password.

---

public/robots.txt

This PR closes #1439. I chose to delete the `Sitemap` property from robots.txt instead of generating a sitemap.xml because it causes less friction. In the case that you want to generate an actual sitemap, I'll close this and recommend a module like [simple-sitemap](https://nuxt.com/modules/simple-sitemap).

Remove sitemap property from robots.txt

---

nuxt.config.ts
package.json
pnpm-lock.yaml

Implements loading of all locale files shipped with Omorphia package by globbing and registering them during the `vintl:extendOptions` hook.
Also updated VIntl for Nuxt to ensure those files are properly loaded. Previous version of VIntl for Nuxt had a somewhat broken module ID tracking, preventing Omorphia locale files to be properly transformed during the build; at least on systems like Windows, don't know about \*nix. The tracking approach was replaced in 1.8.0, and it seems to be working now.

Add Omorphia locale files loading

---

utils/i18n-project-type.ts

This PR adds a fallback to `getProjectTypeMessage` function to return a generic project type whenever it encounters an unknown project type, ensuring there are no errors when the new project types are added.

Fallback to project type message on unknown types

---

helpers/infer.js

It changes the inferring from assuming all mods with a `mods.toml` file is Minecraft Forge to checking if NeoForge is in the dependencies and on 1.20.2 and above only adding Minecraft Forge if `forge` is in the dependencies.

Add NeoForge to infer

---

pages/auth/sign-in.vue

This is one of my pet peeves. I start to type in my 2FA code and realise it hasn't typed it in.
This PR simply adds the [autofocus attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus) to the input form.

Auto-focus 2FA input box

---

locales/en-US/index.json

With new features (like collections), I think there's been an oversight in adding these keys.
https://github.com/search?q=repo%3Amodrinth%2Fknossos%20%22profile.label.no-collections%22&type=code

Fix: Add missing translation keys in index.json

---

pages/[type]/[id]/changelog.vue

This PR is a small change to the changelog page that adds a small increase to the bottom padding.
The changelog bars have absolute positioning with a 0.5rem top offset. This leads to bars at the end of the changelog looking out of place.
Increasing the bottom padding unifies the distance from the top of the changelog card and the bottom for changelog bars:
A potential caveat is that if there is a download button at the end of the changelog it will appear slightly higher than before, which doesn't conform to the existing design patterns, though it still doesn't look bad (right and bottom offset are equal). 
Other, more involved solutions involving changing styling of the changelog bar are likely better long term, but I wanted to modify as little markup as possible.

Added padding to account for .changelog-bar offset

---

pages/organization/[id].vue

Considerations:
* Should the "followers of projects" stat also be on organization pages?
* The stats on organization pages don't use `IntlFormatted`, unlike the ones on user pages

Add download stat on organization pages

---

pages/settings/sessions.vue

Just fix a typo on the sessions.vue file: `scoped` instead of ̀`socped`.

Fix scoped typo

---

pages/dashboard/index.vue

Remove incorrect minimum withdraw amount from dashboard

---

nuxt.config.ts
pages/auth.vue
pages/auth/reset-password.vue
pages/auth/sign-in.vue
pages/auth/sign-up.vue

Supersedes #1677 and Closes #1353

Change to non-interactive turnstile

---

pages/app.vue

This notes the third-party packages available for the Modrinth App on it's page. Links to the article I wrote earlier https://support.modrinth.com/en/articles/9298760

feat: third party packages on app page

---

composables/tag.js
pages/search/[searchProjectType].vue

Right now, when the user clicks on `More` to show the rest of the loaders, the extra loaders are intermixed with the original. This is unitutive, and makes it harder to find what you're looking for and  to see what loaders are the ones behind the more.
This PR fixes that by putting all the loaders hidden by `More` at the bottom of the list
Edit:
Now also fixes #953, which changes the Resource Pack Resolution filters to be OR instead of AND

Move extra loaders and change RP Resolutions to use OR

---

package.json
patches/readable-stream@2.3.8.patch
pnpm-lock.yaml

It seems that Rollup node-resolve module doesn't properly deal with trailing slashes, causing it to think that `string_decoder` is a built-in Node.js dependency and attempt to import it from `unenv`, which will obviously fail, because `string_decoder` is not, in fact, a Node.js dependency, but an individual dependency of `readable-stream`.
This adds a small patch for `readable-stream@2.3.8` dependency, which removes the leading slash, which seems to fix the builds.
This probably should be reported to relevant developers (Rollup node-resolve plugin or Nitro?).

Fix building for Cloudflare Nitro preset

---

nuxt.config.ts

It seems that Nuxt Turnstile's way of setting the key in `runtimeConfig` is broken and doesn't work properly, resulting in an error in runtime, because it has to be set. This PR sets the key in `runtimeConfig` manually instead, which seems to fix the issue.

Fix Turnstile unable to read the siteKey

---

nuxt.config.ts

It seems that Nuxt Turnstile's way of setting the key in `runtimeConfig` is broken and doesn't work properly, resulting in an error in runtime, because it has to be set. This commit sets the key in `runtimeConfig` manually instead, which seems to fix the issue.

Fix Turnstile unable to read the siteKey (#1728)

---

pages/app.vue

***Supersedes #1623***
This pushes bottom transition to a background level while setting it so that any z-indexes are isolated within the hero to avoid any other weirdness from happenning.

Fix transition covering More download options btn
