- components/GoogleAd.vue
- nuxt.config.js
- package-lock.json
> Google Ads

- assets/styles/global.scss
- assets/styles/layout.scss
- components/ModResult.vue
- layouts/default.vue
- pages/mods.vue
> Make responsive

- components/EthicalAd.vue
> fix: word the alt text differently

- assets/styles/global.scss
- assets/styles/highlightjs.scss
- nuxt.config.js
- package-lock.json
- package.json
- pages/index.vue
- plugins/vue-syntax.js
Adds code blocks to replace GIFs of code and a template for documentation code.
> Template Codeblock with example for index.vue

- README.md
Image from https://gist.github.com/MulverineX/6f0a27bc67692f14567816ce1c3f7710 
Resolves #26
> Add in Readme

- components/Categories.vue
- components/Pagination.vue
- components/ProjectCard.vue
- layouts/default.vue
I've fixed a few issues from #50, as well as some problems with icons.
> Accessibility Changes

- pages/user/_id.vue
I noticed that the title of the user page was like the title of the main page, which doesn't really make sense. This is what corrects this PR.
> Fix User Page Title

- components/ProjectCard.vue
> Attempt to fix flex-shrink issue with Safari

- .github/workflows/docker-compile.yml
- Dockerfile
- components/MFooter.vue
- nuxt.config.js
Add experimental support for github actions
> Add version support for the docker builds & local builds

- components/ModPage.vue
- layouts/default.vue
- middleware/auth.js
- nuxt.config.js
- package-lock.json
- package.json
- pages/dashboard/misc/revoke-token.vue
- pages/dashboard/moderation.vue
- pages/dashboard/notifications.vue
- pages/dashboard/projects.vue
- pages/dashboard/settings.vue
- pages/mod/_id/edit.vue
- pages/mod/_id/index.vue
- pages/mod/_id/newversion.vue
- pages/mod/_id/settings.vue
- pages/mod/_id/version/_version/edit.vue
- pages/mod/_id/version/_version/index.vue
- pages/mod/_id/versions.vue
- pages/mod/create.vue
- pages/report/create.vue
- pages/user/_id.vue
- plugins/auth.js
- store/auth.js
> More secure custom authentication solution

- pages/mod/_id/newversion.vue
> Automatic redirection once you create a new version

- .eslintignore
- components/ads/Advertisement.vue
- components/layout/ModPage.vue
- components/ui/ProjectCard.vue
- modules/analytics/lib/constants.js
- modules/analytics/lib/module.js
- modules/analytics/lib/templates/plugin.js
- modules/gpt-ads/lib/constants.js
- modules/gpt-ads/lib/module.js
- modules/gpt-ads/lib/templates/component.js
- modules/gpt-ads/lib/templates/plugin.js
- package.json
- pages/dashboard/privacy.vue
- pages/mods.vue
- pages/user/_id.vue
Added many new features to mobile support, making sure ads doesn't overflow, same for the consent review page.
> Added mobile friendly ads & ads

- components/layout/ModPage.vue
- pages/mod/_id/index.vue
> Fix "Available For" field who is set to None

- pages/dashboard.vue
- pages/dashboard/follows.vue
- pages/dashboard/notifications.vue
- pages/dashboard/privacy.vue
- pages/dashboard/projects.vue
- pages/dashboard/settings.vue
This PR fix missings title for all dashboard pages.
> Fix page title for dashboard

- pages/about.vue
I hate having to deal with prettier by hand
> Add more basic infos to about page

- pages/mod/_id/newversion.vue
- pages/mod/_id/settings.vue
This PR fix the field "Available For" who is set to None on Settings and new version page.
> Fix "Available For" None for Settings mod and new version page

- pages/user/_id.vue
This PR remove the report button on your own user page.
Fix #215
> Fix report button on own uer page

- components/layout/MFooter.vue
- pages/dashboard.vue
- pages/dashboard/follows.vue
- pages/dashboard/misc/revoke-token.vue
- pages/dashboard/notifications.vue
- pages/dashboard/privacy.vue
- pages/dashboard/projects.vue
- pages/dashboard/settings.vue
- pages/index.vue
- pages/mod/_id/edit.vue
- pages/mod/_id/newversion.vue
- pages/mod/_id/settings.vue
- pages/mod/_id/version/_version/edit.vue
- pages/mod/_id/version/_version/index.vue
- pages/mod/create.vue
- pages/mods.vue
- pages/report/create.vue
- privacy-toggles.js
Also converts many title case things to sentence case, and adds a link on the edit mod & create mod pages to the licensing guide
> Adjust quite a bit of wording

- assets/styles/highlightjs.scss
- pages/mod/_id.vue
- pages/mod/_id/edit.vue
- pages/mod/_id/newversion.vue
- pages/mod/_id/version/_version/edit.vue
- pages/mod/_id/version/_version/index.vue
- pages/mod/_id/versions.vue
- pages/mod/create.vue
- pages/mods.vue
A better version of #229.
Also makes fetch on the search page async so that [this](https://discord.com/channels/734077874708938864/734082619352023081/847510062566080572) doesn't happen.
Fixes #239
Implements/closes #251
Fixes #208
> General UI Improvement (again)

- pages/mod/_id.vue
> Wrap mod icon and title in link

- pages/mod/_id.vue
Allows Google search filtering to work with mod titles
> Improve SEO description

- pages/mod/_id.vue
> Correctly handle `""` as custom license URL

- pages/index.vue
> Homepage styling improvements

- layouts/default.vue
> Add `z-index: 20` to user dropdown

- package-lock.json
- pages/user/_id.vue
> Add follow count & user ID to user page

- assets/styles/components.scss
- pages/dashboard.vue
- pages/dashboard/notifications.vue
- pages/mod/_id/version/_version/index.vue
- plugins/compiled-markdown-directive.js
Fixed three minor issues
- JSXSS sanitizing checkboxes #290 
- Typo in version #288 
- Navigation tabs not having proper margins
> Fixed minor issues

- README.md
> Direct people to docs for contributing

- components/ui/SmartFileInput.vue
- nuxt.config.js
- pages/_type/_id.vue
- pages/_type/_id/edit.vue
- pages/_type/_id/gallery.vue
- pages/_type/_id/settings.vue
- pages/_type/_id/version.vue
- pages/_type/_id/versions.vue
- pages/create/report.vue
- pages/search/modpacks.vue
- pages/settings/index.vue
11. Once a file has been added in new version creation, it cannot be removed, so an accidental misclick will cause you to have to restart
12. The popup preventing you from leaving new version creation without confirming is gone
13. Upon creating a new version, it tries taking you to /project/<proj id>/version/<version id> instead of /<proj type>/...
14. On the project edit page and the project edit page exclusively, the license on the side just disappears https://i.imgur.com/IBHdnb3.png
15. Additions, edits, and removals to external links, technical information, or gallery are not shown until the page is refreshed
16. Upload image button on gallery is chunky
17. After editing a version, going to the changelog page has the versions out of order
- `/search` route does nothing
- You can …
> Apiv2-support fixes

- assets/styles/global.scss
- layouts/default.vue
This preliminary, opening the PR just so the maintainers can give their 2cents on the colors chosen.
> New Dark Mode brand colors

- layouts/default.vue
- pages/_type/_id/edit.vue
- pages/_type/_id/settings.vue
- pages/_type/_id/version.vue
- pages/create/project.vue
- pages/moderation.vue
- pages/settings.vue
- pages/settings/index.vue
- pages/settings/privacy.vue
- pages/settings/security.vue
- pages/user/_id.vue
See 286025c's comments for what exactly this addresses - or just look at the "Fix Pushed" column
> Fix various issues reported on the Trello

- assets/styles/global.scss
- assets/styles/layout.scss
- components/ui/ProjectCard.vue
- nuxt.config.js
- pages/_type/_id.vue
- pages/_type/_id/changelog.vue
- pages/_type/_id/gallery.vue
- pages/_type/_id/version.vue
- pages/create/project.vue
- pages/search.vue
- Search Filter: you should be able to select multiple project licenses as well
- Changelog linearity will have duplicate entries for when a mod supports both fabric and forge, or multiple mc versions
- At least in the search, licenses should have short names instead of their long ones
- The clear filters button should fade out when there's no filters to clear
- Horizontal scrollbars breaks bottom curves
- Make scrollbar an overlay on all pages so the site doesn't jump left/right when you switch to a page without a scrollbar
- When selecting a license on the create project page, the dropdown doesn't go away when you click on a license; custom license is unselectable
- On project cards on the search page, followers/downloads label are plural when the value is 1
- On the mod page, in the …
> Fix a lot of bugs - see description

- pages/settings/index.vue
https://canary.discord.com/channels/734077874708938864/734082619352023081/936801072146690079 - "cosmetics toggles v-model the wrong variable"
Also improves formatting of title/description of these options
> Fix issues with new left/right side toggles

- assets/styles/components.scss
- components/ui/Pagination.vue
- components/ui/ProjectCard.vue
- components/ui/ThisOrThat.vue
- pages/index.vue
- Prevent list items in project body from overflowing
- Reduce margin between pagination buttons for better mobile support
- Prevent titles from overflowing in search for better mobile support
- Don't show ThisOrThats with only one item
- Fix style inconsistencies on homepage
- Add more links to homepage to docs, GH, and discord, so they can't be missed
> Bundle of small fixes

- assets/styles/components.scss
- assets/styles/global.scss
- pages/_type/_id/gallery.vue
- pages/settings/index.vue
Also added a "hidden" developer mode that lets you temporarily switch the API between production and staging. Access developer mode by clicking your profile icon six times in the settings page, and the option appears.
Closes #366
> Add expanding gallery images by clicking on them

- pages/_type/_id/changelog.vue
> Fix download buttons in the changelog page

- components/ui/Badge.vue
- components/ui/VersionFilterControl.vue
- pages/_type/_id/changelog.vue
- pages/_type/_id/gallery.vue
- pages/_type/_id/versions.vue
- pages/search.vue
Changelog page:
Versions page:
Closes #335
> Add version filter controls to Changelog and Versions pages

- assets/images/utils/download-alt.svg
- assets/images/utils/download.svg
- components/ui/ProjectCard.vue
- pages/settings/index.vue
- pages/user/_id.vue
> Improve the file download icon so it's more obviously a download icon

- layouts/default.vue
Should fix some of the font issues some people are having with the symbol icon
> Use dropdown SVG for profile dropdown

- assets/styles/global.scss
- layouts/default.vue
> Fix bad contrast ratio with secondary text in dark mode

- components/ui/VersionFilterControl.vue
> Fix sorting on version filtering

- assets/styles/components.scss
- components/ui/VersionFilterControl.vue
> Improve Multiselect styling to not overlap other elements

- pages/_type/_id/version.vue
> Add Minecraft version snapshot filter to version edit/create page

- assets/styles/components.scss
- components/ui/VersionFilterControl.vue
- pages/_type/_id.vue
- pages/_type/_id/changelog.vue
- pages/_type/_id/gallery.vue
- pages/_type/_id/versions.vue
> Make links on project pages more consistent, fix some selectors showing when they shouldn't

- assets/styles/components.scss
- assets/styles/global.scss
- components/ui/Pagination.vue
- components/ui/ProjectCard.vue
- pages/_type/_id.vue
- pages/create/project.vue
- pages/index.vue
- pages/search.vue
- pages/settings/index.vue
I know some of the media queries look a bit insane but trust me it works lol
Closes #394
Closes #393
> Continue the cleanup train

- assets/images/utils/contract.svg
- assets/images/utils/expand.svg
- pages/_type/_id/gallery.vue
- Added image description
- Made controls less obtrusive when not hovering over them
- Displays maximum of native image size by default (Closes #407)
- Toggle to an expanded mode which will fill your screen
- Clicking out of the modal once again closes it (Closes #405)
> Even more gallery improvements

- pages/_type/_id/edit.vue
- pages/create/project.vue
> Add an indicator for required fields

- nuxt.config.js
fixes #440, fixes #436 too somehow
> Make newlines behave like GitHub

- assets/styles/components.scss
- components/ui/ProjectCard.vue
- nuxt.config.js
- pages/_type/_id.vue
- pages/notifications.vue
- pages/search.vue
> Add modpack page warning + Fix notifications nav titles

- layouts/default.vue
> Add modpacks icon on mobile

- pages/search.vue
> History spam fix

- assets/styles/utils.scss
- package-lock.json
Incrased line hights from default to 1.3 at text boxes.
> Fixed GitHub Issue #423

- pages/_type/_id/version.vue
No more annoying spaces, numbers or special characters.
The way i'we done it is probably not the best, but it works!
Fixed GitHub Issue #467
> Project ID removes spaces (Issue #467)

- nuxt.config.js
- pages/search.vue
Closes #482. I picked `g` because it comes right after `f` but it could be anything.
> Save OR facets in query string

- components/ui/VersionFilterControl.vue
It's really not our place to be imposing a default loader on people, especially as we start adding more loaders
> Fix #485 by removing default loader from version filters

- assets/styles/global.scss
- pages/_type/_id/gallery.vue
> Fix gallery floating buttons and text in light mode

- components/ui/SmartFileInput.vue
- pages/_type/_id/gallery.vue
- pages/_type/_id/version.vue
- pages/create/project.vue
Closes #489
Changed the style to match the icon selection
> Improved styling of the version file upload button

- pages/index.vue
> Give Modpacks a check mark since it's in alpha

- assets/styles/global.scss
> Fixes the font weight of code blocks to use regular instead of medium

- package.json
- pnpm-lock.yaml
- src/components/elements/Ad.svelte
- src/components/elements/FileDropzone.svelte
- src/components/elements/ImageUpload.svelte
- src/components/elements/Popup.svelte
- src/components/layout/Footer.svelte
- src/components/layout/Header.svelte
- src/components/layout/MobileBar.svelte
- src/hooks/cache.ts
- src/routes/[search=searchType].svelte
- src/routes/[type=projectType]/[identifier]/__layout.svelte
- src/routes/[type=projectType]/[identifier]/gallery.svelte
- src/routes/[type=projectType]/[identifier]/index.svelte
- src/routes/[type=projectType]/[identifier]/settings.svelte
- src/routes/[type=projectType]/[identifier]/version/[version].svelte
- src/routes/__layout.svelte
- src/routes/discord.ts
- src/routes/following.svelte
- src/routes/index.svelte
- src/routes/legal/privacy.svelte
- src/routes/legal/rules.svelte
- src/routes/legal/terms.svelte
- src/routes/moderation/__layout.svelte
- src/routes/notifications.svelte
- src/routes/settings.svelte
- src/routes/user/[identifier]/__layout.svelte
*except legal pages and moderation page
> Dehardcode *everything* for i18n

- layouts/default.vue
- nuxt.config.js
> fix 'unknown' version in footer

- pages/_type/_id.vue
> Added missing PolyMC link from modpack pages.

- pages/settings/index.vue
Also potentially resolves #504
> Make system theme selectable

- pages/_type/_id.vue
> Fix donation URLs hidden when there's no external links

- pages/_type/_id.vue
Co-authored-by: Essem <smswessem@gmail.com>
> Hotfix #512 not showing the correct date

- pages/_type/_id/edit.vue
Tested and seems to work perfectly.
Fixes https://github.com/modrinth/knossos/issues/421
> Fix custom license being empty when editing a project.

- pages/_type/_id/version.vue
- pages/create/project.vue
Closes #545 as not planned
Related to modrinth/docs#50
> Add note about adding multiple files to a version

- assets/styles/components.scss
- assets/styles/global.scss
- pages/_type/_id.vue
- pages/_type/_id/version.vue
- pages/create/project.vue
- pages/search.vue
The 'abandoned' status doesn't yet exist, but this is future-proofing
> Add more banners and warnings for some statuses & other fixes

- pages/_type/_id.vue
- pages/legal/privacy.vue
- pages/legal/rules.vue
- pages/legal/terms.vue
> Implement new content rules

- nuxt.config.js
As said by Emma here: https://discord.com/channels/734077874708938864/734077874708938867/1001533787861164172
(Might get useless as seen further in the discussion with shipping the font directly)
> Switch from google fonts to bunny

- nuxt.config.js
Should work if the uploaded file is right from the CDN as [wafflecoffee](https://github.com/wafflecoffee) postend in #581
> Change the link to Modrinth CDN from #581

- assets/styles/global.scss
- plugins/xss.js
* added kbd tag to whitelist in `plugins/xss.js`
* added styles for the kbd selector in `assets/styles/global.scss`
> added support for the kbd tag in markdown editor

- pages/_type/_id/version.vue
Had to close and reopen #578 in a different PR because I had some merge issues. Should be fixed now.
> Enhance version creation

- pages/_type/_id/gallery.vue
> Fix special characters in gallery title/description

- pages/_type/_id.vue
- pages/search.vue
Adds the Prism launcher to the modpack info stuff
> Add Prism Launcher

- layouts/default.vue
> Add more footer links

- assets/styles/components.scss
- components/ui/Chips.vue
- layouts/default.vue
- pages/_type/_id/edit.vue
- pages/settings/follows.vue
- pages/user/_id.vue
Show settings button in hamburger menu when signed out on mobile, fix chip outlines so they work on iOS, rename mods -> projects in followed projects list.
> Tiny fixes

- components/ui/ModalCreation.vue
> Fix 404 error when creating a resource pack

- pages/_type/_id.vue
> Fix project layout on right not working correctly

- assets/styles/components.scss
- components/ui/ModalTransfer.vue
- layouts/default.vue
- pages/dashboard/index.vue
- pages/dashboard/revenue.vue
- pages/index.vue
- plugins/shorthands.js
- Removed WIP text on home page for monetization
- Fixed beta badge label style
> CMP Update Hotfixes

- package-lock.json
List of changes in Vue 2.7:
https://blog.vuejs.org/posts/vue-2-7-naruto.html
> Bump Vue to 2.7

- assets/styles/components.scss
- pages/_type/_id.vue
- pages/user/_id.vue
> Make download/follower displays consistent

- assets/styles/components.scss
- pages/_type/_id/edit.vue
- pages/_type/_id/gallery.vue
- pages/_type/_id/version.vue
Closes #416
Closes #475
Closes #525
> Fix text box resizing

- pages/settings/account.vue
https://streamable.com/xucr2e
Fixes #618
> Improve user deletion workflow

- assets/styles/components.scss
- components/ui/Modal.vue
- layouts/default.vue
- middleware/analytics.js
- nuxt.config.js
- pages/_type/_id.vue
- pages/about.vue
- pages/index.vue
- pages/search.vue
- pages/settings/index.vue
- pages/user/_id.vue
- plugins/shorthands.js
- store/cosmetics.js
> Add feature flag for opening external links in a new tab

- components/ui/ProjectCard.vue
- pages/_type/_id.vue
- pages/user/_id.vue
Mod messages w/o body:
Mod messages with body:
> Massively improved moderator message visibility

- assets/styles/components.scss
- assets/styles/global.scss
> Improve accessibility on contrast themes

- assets/images/utils/archive.svg
- assets/images/utils/box.svg
- assets/styles/components.scss
- assets/styles/global.scss
- components/ui/Badge.vue
- components/ui/FileInput.vue
- components/ui/ModalTransfer.vue
- components/ui/ProjectCard.vue
- layouts/default.vue
- pages/_type/_id.vue
- pages/_type/_id/changelog.vue
- pages/_type/_id/edit.vue
- pages/_type/_id/settings.vue
- pages/_type/_id/version.vue
- pages/_type/_id/versions.vue
- pages/index.vue
- pages/moderation.vue
- pages/user/_id.vue
- plugins/shorthands.js
Examples of the new badges and color scheme in action:
> Improve badges and work on a more unified color scheme for random colors

- pages/user/_id.vue
> Fix user page err

- layouts/default.vue
> Fix header spacing

- assets/styles/global.scss
- components/ui/ModalCreation.vue
- components/ui/ProjectCard.vue
- layouts/default.vue
- nuxt.config.js
- pages/_type/_id.vue
- pages/_type/_id/edit.vue
- pages/moderation.vue
- pages/search.vue
- pages/search/shaders.vue
- pages/settings/index.vue
- plugins/shorthands.js
- store/cosmetics.js
- store/tag.js
> Shaderpack support

- pages/_type/_id.vue
> make long Projectnames wrap with a '-'

- plugins/shorthands.js
Fixes #736 and #782
This has some minor code duplication but it's the best idea I could think of, all things considered. Let me know if something could use improvement.
> Fix formatting of money values

- assets/styles/components.scss
- components/ui/DropArea.vue
- components/ui/ModalCreation.vue
- components/ui/ProjectCard.vue
- layouts/default.vue
- pages/_type/_id.vue
- pages/_type/_id/changelog.vue
- pages/_type/_id/edit.vue
- pages/_type/_id/gallery.vue
- pages/_type/_id/version.vue
- pages/_type/_id/versions.vue
- pages/moderation.vue
- pages/search.vue
- pages/settings/follows.vue
- pages/user/_id.vue
- plugins/fileUtils.js
- plugins/shorthands.js
- store/tag.js
> New gallery creation/editing/deleting UI

- components/ui/Badge.vue
- pages/_type/_id.vue
- pages/_type/_id/edit.vue
- pages/moderation.vue
Also incorporates changes from #810
> Treat withheld as unlisted (prod)

- pages/_type/_id/gallery.vue
- pages/_type/_id/settings/license.vue
- pages/_type/_id/version.vue
> Fix various gallery issues reported on Discord

- pages/_type/_id/version.vue
> Fix version changelog overflowing (#855)

- pages/_type/_id/version.vue
- pages/_type/_id/version/latest.vue
/version/latest works with a ?loader=<loader> query to filter by loader as well as a ?version=<mc version> query to filter by Minecraft versions
Closes #830
> Add latest version URLs

- plugins/fileUtils.js
> Add support for loading Implementation-Version from MANIFEST.MF for Forge mods

- components/ui/ModalCreation.vue
- pages/_type/_id/settings/index.vue
- pages/_type/_id/settings/links.vue
- pages/_type/_id/settings/members.vue
Reported on discord https://discord.com/channels/734077874708938864/783153806531100673/1062684267026583582
Also fixes #850
> Fix project settings not allowing you to remove links & trim certain project fields

- pages/_type/_id/version.vue
Gives the user a warning message when they try to add a duplicate dependency
Closes #468
> Prevent user from adding the same dependency multiple times

- components/ui/ModalCreation.vue
- components/ui/ProjectPublishingChecklist.vue
- pages/_type/_id/settings/license.vue
> Remove default description and license and add checklist nag for license

- pages/_type/_id/versions.vue
> Add featured icon to featured versions on versions page

- components/ui/ProjectPublishingChecklist.vue
- pages/notifications.vue
One with the notifications page crashing and the other with some console spam on project pages.
> Fix a couple of misc. page errors I noticed

- components/ui/VersionFilterControl.vue
> Add release channel filter to versions pages

- components/ui/ModalModeration.vue
- pages/_type/_id.vue
- pages/moderation.vue
- plugins/fileUtils.js
> Fix moderation queue, moderation status card when approved, and invalid datapack packages

- assets/styles/global.scss
- components/ui/Modal.vue
- pages/index.vue
- pages/search.vue
- Fixes search layout setting being broken
- Fixes landing page stuttering issues
- Fixes modal animation not working
- Fixes title max width being broken
> Landing + other fixes

- .eslintrc.js
- components/ui/ModalReport.vue
- components/ui/ProjectPublishingChecklist.vue
- layouts/default.vue
- layouts/error.vue
- pages/_type/_id.vue
- pages/_type/_id/settings/members.vue
- pages/_type/_id/version.vue
- pages/legal/rules.vue
- pages/user/_id.vue
- store/tag.js
> Miscellaneous fixes relating to statuses, et al

- middleware/analytics.js
- nuxt.config.js
the site privacy policy will be updated when this is in production
> Sync analytics w/ api changes

- components/ui/NavStackItem.vue
Fixes #956
Current behavior:
New behavior:
> Adjust nav-link border radius when focused (fix #956)

- pages/_type/_id.vue
Simple one-line stopgap measure
> Make mod message card background red to stand out more

- assets/styles/global.scss
> Fix oled mode table alt color

- nuxt.config.js
- pages/[type]/[id].vue
- pages/dashboard/index.vue
- pages/dashboard/revenue.vue
- pages/search/[searchProjectType].vue
- pages/settings/account.vue
- pages/settings/monetization.vue
- pages/user/[id].vue
~~This PR modifies the `useBaseFetch` composable to use Nuxt 3's `useLazyFetch` composable.~~
~~Near as I can tell, `useLazyFetch` requires the method to be used either at the top-level of a `<script setup>` or in a lifecycle method. As of creating this PR, I haven't had any success getting it to work inside onMounted.  Consequently, I've gone and converted the search page into a `<script setup>` type of component so I could work with things a bit easier. Due to a lot more code being top-level now, I do think we need to move, some of the code in the search page to helpers, composables, and components we render in the page - wherever it makes sense. The page itself feels a bit bloated. Since this branch was meant to fix the stuttering and get the search page to be more fluid, such …
> Nuxt 3 Lazy Loading Search

- assets/styles/components.scss
- pages/[type]/[id].vue
- pages/search/[searchProjectType].vue
> Fix square button

- components/ui/VersionFilterControl.vue
- composables/query.js
- pages/[type]/[id]/changelog.vue
- pages/[type]/[id]/versions.vue
- pages/search/[searchProjectType].vue
- plugins/scroll.client.js
- server/plugins/theme.js
> Fix serverless crash + Version Filters on reload

- components/ui/ModalConfirm.vue
> Adds margin to confirmation-text.

- helpers/infer.js
- helpers/parse.js
- pages/[type]/[id]/settings/links.vue
Fixes #937
Fixes #983
Fixes #1056
Fixes #1057
> Small fixes

- plugins/shorthands.js
> Fix the possibility of empty game version range outputs

- composables/cosmetics.js
- layouts/default.vue
This reverts commit 02a82e1e5911c78e3109a1eee0489875379206ec.
> Remove April Fools 2023 "beta" prompt

- pages/[type]/[id]/settings/index.vue
> Fix project icon label in settings id linking to project name

- assets/styles/components.scss
> Fix nested lists having bottom margins Fixes #1033

- pages/[type]/[id].vue
- pages/[type]/[id]/version/[version].vue
- plugins/shorthands.js
This may seem like a bit of an odd way to fix it but it works well. Left a note in the code so we know why it's done that way
Fixes #842
Closes MOD-357
> Fix duplicate version featured links being wrong sometimes

- pages/dashboard/index.vue
- plugins/shorthands.js
Money will now consistently round down
> Fix money rounding issue

- assets/images/utils/history.svg
- assets/styles/components.scss
- components/ui/Badge.vue
- components/ui/Breadcrumbs.vue
- pages/[type]/[id].vue
- pages/[type]/[id]/version/[version].vue
- pages/dashboard/projects.vue
- pages/dashboard/revenue/index.vue
- pages/dashboard/revenue/transfers.vue
- pages/index.vue
> Add transfer history and unify back elements with breadcrumbs

- pages/dashboard/projects.vue
Also clears the modal contents after completion - doesn't clear on error to prevent annoyance.
> Fix bulk link editing (Fixes #1087)

- layouts/default.vue
> Fix mobile navbar spacing

- helpers/parse.js
The previous PR got through because GitHub conveniently decided not to run the lint check on it...
> Fix lint issues

- pages/dashboard/projects.vue
https://user-images.githubusercontent.com/93472213/230476485-59daa9ef-116e-43eb-8e3a-eae4198dfb9d.mp4
> Ascending/Descending order by button for projects dashboard page.

- helpers/parse.js
This changes Highlight.js class parsing when it comes to multiple classes
> Fix hljs class parsing

- pages/[type]/[id]/version/[version].vue
> do not allow empty option on dropdown when adding dependency

- components/ui/Pagination.vue
- pages/[type]/[id]/changelog.vue
- pages/[type]/[id]/versions.vue
Basically #1089 without the input field
Closes https://github.com/modrinth/knossos/issues/392
> Fix pagination

- pages/[type]/[id].vue
Fixes the issue Described here: #1184 
Fix:
- Converted the `@click` and the div element to a `NuxtLink` that will act as an ancher.
> Fix CTRL clicking on versions issue

- pages/[type]/[id].vue
fixes #1158 
Fix:
- replacing the redirection
> fixed redirection back to followed projects

- layouts/default.vue
> fix logging out doesnt work

- assets/styles/components.scss
> fixed detail tab with summary and bold tags

- components/ui/VersionFilterControl.vue
- pages/[type]/[id]/versions.vue
> fix version filtering wrong page

- layouts/default.vue
> Get the app button

- pages/[type]/[id]/settings/members.vue
Fixed the "leave project" button that sent an error and didn't worked
> Fixed Leave Project button

- pages/[type]/[id]/moderation.vue
- Fixes a bug where project threads would show up as unread when changing its status
- Adds a note about the extended delays
- Use omorphia
> Project moderation tab improvements

- .github/workflows/regenerate.yml
also, shameless plug but check out #1200 kthx byee
> Skip regenerate workflow on forks

- layouts/default.vue
> Fix: Notifications are always unread on small windows

- pages/dashboard/index.vue
> Fix: Incorrect notification history link on dashboard

- pages/[type]/[id]/version/[version].vue
| Before: | After: |
|-|-|
| ![image](https://github.com/modrinth/knossos/assets/60205699/65c789c4-8f2b-48f5-9955-1d5485f0e93e) | ![image](https://github.com/modrinth/knossos/assets/60205699/6db76c15-072a-4518-9bd2-88ff35fca340) |
> Fix dependency capitalization

- .github/ISSUE_TEMPLATE/config.yml
- error.vue
- layouts/default.vue
- pages/settings/account.vue
> Update Discord invite link to use official

- middleware/wellknown.global.ts
- server/routes/.well-known/change-password.ts
All is in the title.
I think we can deploy this PR to test if password manager can use this ^^.
Close #1317
> Make .well-known/change-password redirect appropriately

- pages/settings/pats.vue
> Fix "Incorrect wording for expired pats"

- locales/en-US/index.json
- pages/settings/sessions.vue
- pages/user/[id].vue
- utils/common-messages.ts
> Add translation keys for Sessions page

- pages/settings/pats.vue
> Token Modal confirm for removal

- pages/settings/sessions.vue
Noticed a couple more things, but #1381 was already merged :D
- Fix separator spacing
- Remove quote character from title
> Post translation Sessions settings page fixes

- pages/settings.vue
> Add sessions translation to settings navstack

- pages/legal.vue
- pages/legal/ccpa.vue
- pages/legal/cmp-info.vue
- pages/legal/cmp.vue
- pages/legal/copyright.vue
- pages/legal/privacy.vue
- pages/legal/rules.vue
- pages/legal/terms.vue
https://rules-update.knossos.pages.dev/legal/rules
> Update legal pages, especially rules

- components/ui/Avatar.vue
- components/ui/Badge.vue
> Convert Avatar & Badge components to Composition API

- components/ui/Avatar.vue
> Fix convertion to Composition API for Avatar component

- error.vue
> Convert error page to Composition API and fix condition for 404 Logo

- package.json
- pnpm-lock.yaml
This PR resolve the problem of rounding account age on the profile.
Thanks to @brawaru for the reactivity ^^.
Before :
After:
> Update to @vintl/how-ago 3.0.1

- pages/[type]/[id]/version/[version].vue
> Fixed report icons on version page when logged out

- pages/auth/sign-up.vue
- pages/auth/welcome.vue
> Fixed aria-label on Subscribe Button

- package.json
- pages/[type]/[id]/gallery.vue
- pages/settings/pats.vue
- pnpm-lock.yaml
This may help for #1405.
Close #1412.
> Update to omorphia 0.6.2

- pages/search/[searchProjectType].vue
This reverts commit 5472ea08746533c8b50aff4cefb24882311dceda.
> Revert download sort again

- pages/settings/account.vue
> Fixed Password matching msg showing when confirm is empty

- pages/settings/account.vue
> Fix: "Set Password" button on profile page is not active

- layouts/default.vue
> Fix: Add collections to mobile nav instead of follow (broken link)

- pages/collection/[id].vue
Close #1524 
https://github.com/modrinth/knossos/blob/a037d24b0fee90ca91ad36a53be5367ec5ace0ae/pages/organization/%5Bid%5D.vue#L179
> Fix: Wrong follower count on collections

- components/ui/thread/ConversationThread.vue
- components/ui/thread/ThreadMessage.vue
> Add report reopening and message for reopening a report

- pages/dashboard/revenue/transfers.vue
> Add filters for transfer history page

- pages/collection/[id].vue
> Fix: Error for "updated tooltip" on collection page

- pages/collection/[id].vue
> Fix: Project banners aren't showing in collections

- pages/settings/account.vue
It's a QOL for account management.
> Add enter shortcut for 2FA & email management

- pages/[type]/[id]/moderation.vue
> Fix: Minor grammar mistake in project Moderation page

- pages/[type]/[id].vue
> Fix: Copy ID button doesn't work

- pages/collection/[id].vue
> Fix: Projects in collections have less tags shown that they have

- pages/[type]/[id]/settings/members.vue
Closes #1478
(Original pull deleted due to merge confilcts)
> [simple]: add title to leave project button

- locales/en-US/index.json
- pages/settings/sessions.vue
Related to https://github.com/Mysterious-Dev/knossos/pull/9
> Rework session translation keys for normalization

- pages/[type]/[id]/settings/links.vue
also converted to composition API
> Fix donation links in project settings

- pages/settings/index.vue
> Use Composition API for settings index

- pages/auth/reset-password.vue
- pages/auth/sign-in.vue
- pages/auth/sign-up.vue
> Use omorphia icons for auth pages

- layouts/default.vue
- locales/en-US/index.json
- Re-organize default layout messages
- Fix navRoutes not being computed in default layout
- Fix untranslated Get Modrinth App buttons in default layout
- Make legal disclaimer in the default layout translatable
> Follow-up fixes for #1616

- pages/[type]/[id]/moderation.vue
> Add review delay link to moderation page

- pages/collection/[id].vue
- pages/organization/[id].vue
> Fix missing categories and environments on orgs and following collection

- pages/settings/index.vue
> Fix theme preview width

- layouts/default.vue
- pages/settings/index.vue
- plugins/1.theme.js
> Fix system theme not respecting preferred dark theme.

- pages/[type]/[id].vue
> Fix project header shadow

- pages/legal/cmp-info.vue
Analytics were introduced in [PR #1483](https://github.com/modrinth/knossos/pull/1483), which was previously not mentioned on the https://modrinth.com/legal/cmp-info page.
> Update Rewards Program Information because the analytics dashboard has been released

- package.json
- pnpm-lock.yaml
updating `vue3-apexcharts` should fix #1582
at least locally it does for me
> fix: weird graph rendering
